# # This workflow will install Python dependencies, run tests and lint with a single version of Python
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

# name: CD pipeline

# on:
#   push:
#     branches: 
#       - main

# permissions:
#   contents: read

# jobs:
#   deploy:
#     name: CD process
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4

#     - name: Deployment
